name: Test Design
description: テスト設計用のIssueテンプレート
title: "[🔖 Dev]: "
labels: ["dev"]

body:
  - type: markdown
    attributes:
      value: |
        テスト設計に関するテンプレートです。全機能を横断するような機能を開発する際にご利用ください。

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認観点
      description: 下記観点を考慮していることを確認ください
      options:
        - label: 画面遷移
          required: false
        - label: データパターン
          required: false
        - label: ローカル上の確認観点
          required: false
        - label: dev 環境上の確認観点
          required: false
        - label: stg 環境上の確認観点
          required: false
  
  - type: textarea
    id: relative-issue
    attributes:
      label: 関連Issue
      description: |
        関連Issueのリンクを記載ください
      value: |
        -
    validations:
      required: true
        
  - type: textarea
    id: test-design
    attributes:
      label: テスト設計
      description: |
        以下にテスト設計を記載ください
      value: |
