name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: [bug, triage]
assignees: 
- octocat
- github-bot

body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please make sure you've completed the following steps before submitting your issue.
      options:
        - label: I have searched the existing issues
          required: true
        - label: I have provided detailed steps to reproduce the issue
          required: true
        - label: I have included the version of the software I am using
          required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: "A clear and concise description of what the bug is."
      placeholder: "Tell us what happened..."
      value: ""
    validations:
      required: true
