name: PBI
description: PBI(Product Backlog Item)用のIssueテンプレートです
title: "[PBI]: "
labels: ["pbi"]
# projects: ["octo-org/1", "octo-org/44"]
body:
  - type: markdown
    attributes:
      value: |
        PBI(Product Backlog Item)を記載します
  - type: input
    id: problem
    attributes:
      label: 問題
      description: どのような問題がありますか
    validations:
      required: true
  - type: textarea
    id: user-story
    attributes:
      label: 実現したいこと・ユーザーストーリー
      description: 「誰 (ペルソナ)」が「何 (機能やサービス)」を「なぜ (価値)」を求めているのでしょうか
      value: |
        ## ペルソナ
        - 
        ## 機能やサービス
        - 
        ## 価値
        - 
    validations:
      required: true
  - type: textarea
    id: sbi
    attributes:
      label: SBI
      description: |
        PBIに紐づくSBIを列挙します
        PBI起票時は記載なしで問題ありません
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 受入れ基準
      description: |
        結合テストの正常系シナリオのインプットとなります
        PBIに紐づくSBIにて定義するためPBI起票時は記載なしで問題ありません
    validations:
      required: false
