name: SBI
description: SBI(Sprint Backlog Item)用のIssueテンプレートです
title: "[SBI]: "
labels: ["sbi"]
# projects: ["octo-org/1", "octo-org/44"]
body:
  - type: markdown
    attributes:
      value: |
        SBI(Product Backlog Item)の目的を記載します
  - type: textarea
    id: pbi
    attributes:
      label: PBI
      description: |
        SBIが紐づく親PBIのリンクを記載ください
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: 目的
      description: PBIに対し、何を実現するためのSBIでしょうか
    validations:
      required: true
